version: 2
machine:
jobs:
  build:
    working_directory: ~/etg_e2e
    docker:
      - image: node:4.6.0
    steps:
      - checkout
      - run: 
        name: install cypress
        command: npm install -g cypress-cli
    steps:
      - run:
        name: run cypress e2e tests
        command: cypress run