version: 2
jobs:
  build:
    working_directory: ~/etg_e2e
    docker:
      - image: bahmutov/cypress-image:node-6-cypress-0.19.2
    steps:
      - checkout
      - run:
          name: run cypress e2e tests
          command: cypress run
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: test-results/