version: 2
machine:
jobs:
  build:
    working_directory: ~/etg_e2e
    docker:
      - image: node:4.6.0
    steps:
      - checkout
      - run: 
          name: install cypress
          command: npm install -g cypress-cli
      - run:
          name: run cypress e2e tests
          command: cypress run
      - store_artifacts:
          path: test-reports/
          destination: tr1
       - store_test_results:
          path: test-reports/